ymdisc/activity/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (WelcomeView, SummaryView, SectionView, ItemCreateView, ItemEditView, ItemDeleteView,
                    CommentCreateView, CommentEditView, CommentDeleteView)

app_name = 'activity'

urlpatterns = [
    path('welcome/', login_required(WelcomeView.as_view()), name='welcome'),
    path('<int:activity_index>/', login_required(SummaryView.as_view()), name='summary'),
    path('<int:activity_index>/<int:section_index>/', login_required(SectionView.as_view()), name='section'),
    path('<int:activity_index>/<int:section_index>/create_item/',
         login_required(ItemCreateView.as_view()), name='item_create'),
    path('<int:activity_index>/<int:item_pk>/edit_item', login_required(ItemEditView.as_view()), name='item_edit'),
    path('<int:activity_index>/<int:item_pk>/delete_item',
         login_required(ItemDeleteView.as_view()), name='item_delete'),
    path('<int:activity_index>/<int:item_pk>/create_comment/',
         login_required(CommentCreateView.as_view()), name='comment_create'),
    path('<int:activity_index>/<int:comment_pk>/edit_comment/',
         login_required(CommentEditView.as_view()), name='comment_edit'),
    path('<int:activity_index>/<int:comment_pk>/delete_comment/',
         login_required(CommentDeleteView.as_view()), name='comment_delete')
]

ymdisc/mail/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import SendMail

app_name = 'mail'

urlpatterns = [
    path('', login_required(SendMail.as_view()), name='send-mail'),
]

ymdisc/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

ymdisc/templates/base.html
{% load static %}

<! DOCTYPE html >

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
              integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">

        {% block title %}<title>SB Youth Ministry{% endblock %}</title>

        {% block head %}
        {% endblock %}

    </head>

    <body>

        {% include "header.html" %}

        <main>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        {% include "footer.html" %}

        <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous"></script>

        <script>
            // Get the current year for the copyright
            $('#year').text(new Date().getFullYear());
        </script>

        {% block body %}
        {% endblock %}

    </body>

</html>

ymdisc/templates/footer.html
{% load static %}

{% block footer %}

    <footer>
        <p class="text-small text-center mt-3">
            Saint Basil Youth Ministry Discussion Website &copy <span id="year"></span>
        </p>
    </footer>


{% endblock %}

ymdisc/templates/header.html
{% load static %}

{% block header %}

    <header>
        <div class="container">
            <div class="row">
                <!-- St. Basil Icon Logo -->
                <div class="col-md-1 d-none d-md-inline">
                    <a href="{% url 'activity:welcome' %}" class="brand">
                        <img src="{% static 'images/StBasilIcon.png' %}" class="img-fluid">
                    </a>
                </div>
                <div class="col">
                    <!-- Banner Heading -->
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'activity:welcome' %}">
                                <h1 class="banner d-inline">Saint Basil Youth Ministry Discussion</h1>
                            </a>
                        </div>
                    </div>
                    <!-- Welcome and Login/Logout Links -->
                    <div class="row align-items-top">
                        <div class="col-6">
                            {% if user.is_authenticated %}
                                <span class="h5">Welcome {{ user.first_name }}!</span>
                                <a class="link" href="{% url 'user:logout' %}">  (Logout)</a>
                            {% else %}
                                <span class="h5">Welcome!</span>
                                <a class="link" href="{% url 'user:login' %}?next={{ request.path_info }}">  (Login)</a>
                            {% endif %}
                        </div>
                        <!-- Menu Links -->
                        <div class="col">
                            <nav class="navbar navbar-light navbar-expand-lg pt-0">
                                <button class="navbar-toggler ml-auto p-0 pb-3" type="button"
                                        data-toggle="collapse" data-target="#navbarCollapse">
                                    <span class="navbar-toggler-icon pt-1" style="background:none">
                                        <i class="fas fa-bars"></i>
                                    </span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarCollapse">
                                    <div class="navbar-nav ml-auto nav-fill">
                                        {% if user.is_staff %}
                                            <a href="{% url 'mail:send-mail' %}"
                                               class="nav-item nav-link text-right pb-3">
                                                E-mail
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

{% endblock %}