ymdisc/activity/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (WelcomeView, SummaryView, SectionView, ItemCreateView, ItemEditView, ItemDeleteView,
                    CommentCreateView, CommentEditView, CommentDeleteView)

app_name = 'activity'

urlpatterns = [
    path('welcome/', login_required(WelcomeView.as_view()), name='welcome'),
    path('<int:activity_index>/', login_required(SummaryView.as_view()), name='summary'),
    path('<int:activity_index>/<int:section_index>/', login_required(SectionView.as_view()), name='section'),
    path('<int:activity_index>/<int:section_index>/create_item/',
         login_required(ItemCreateView.as_view()), name='item_create'),
    path('<int:activity_index>/<int:item_pk>/edit_item', login_required(ItemEditView.as_view()), name='item_edit'),
    path('<int:activity_index>/<int:item_pk>/delete_item',
         login_required(ItemDeleteView.as_view()), name='item_delete'),
    path('<int:activity_index>/<int:item_pk>/create_comment/',
         login_required(CommentCreateView.as_view()), name='comment_create'),
    path('<int:activity_index>/<int:comment_pk>/edit_comment/',
         login_required(CommentEditView.as_view()), name='comment_edit'),
    path('<int:activity_index>/<int:comment_pk>/delete_comment/',
         login_required(CommentDeleteView.as_view()), name='comment_delete')
]

ymdisc/mail/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import SendMail

app_name = 'mail'

urlpatterns = [
    path('', login_required(SendMail.as_view()), name='send-mail'),
]

ymdisc/activity/models.py
from django.db import models
from django.conf import settings


class Activity(models.Model):
    index = models.SmallIntegerField(unique=True)
    title = models.CharField(max_length=100)
    overview = models.CharField(max_length=512, blank=True)
    publish_date = models.DateField(null=True)
    archive = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['index']
        verbose_name_plural = 'activities'


class Section(models.Model):
    index = models.SmallIntegerField()
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, default='')
    instructions = models.CharField(max_length=512)
    link_name = models.CharField(max_length=50, blank=True)
    link = models.URLField(default="", blank=True)
    visible = models.BooleanField(default=False)

    def __str__(self):
        return self.activity.title + " Section " + str(self.index)

    def save(self, *args, **kwargs):    # set the default value of visible to true for the first section
        if self.index == 1:
            self.visible = True
        super(Section, self).save(*args, **kwargs)

    class Meta:
        ordering = ['index']
        unique_together = ('activity', 'index')


class Item(models.Model):
    index = models.SmallIntegerField()
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    text = models.CharField(max_length=512)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.section) + " Item " + str(self.index)

    def get_comments(self):
        return self.comment_set.all()

    class Meta:
        ordering = ['index']
        unique_together = ('section', 'index')


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    text = models.TextField()
    comment_date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Comment by " + self.user.first_name + " on " + str(self.item)

    class Meta:
        ordering = ['comment_date_time']


class ImageQuote(models.Model):
    title = models.CharField(max_length=50)
    image_filename = models.CharField(max_length=50)

    def __str__(self):
        return self.title

ymdisc/activity/views.py
from django.shortcuts import render, redirect
from django.views import View

import datetime

import utilities

from .models import Activity, Section, Item, Comment

class WelcomeView(View):
    template_name = 'activity/welcome.html'

    def get(self, request):
        activities = Activity.objects.filter(publish_date__lte=datetime.date.today(), archive=False)
        context = {'activities': activities, 'image': utilities.get_quote_image()}
        return render(request, self.template_name, context)


class SummaryView(View):
    template_name = 'activity/summary.html'

    def get(self, request, activity_index):
        activity = Activity.objects.get(index=activity_index)
        sections = Section.objects.filter(activity=activity, visible=True)
        context = {'activity': activity, 'sections': sections}
        return render(request, self.template_name, context)


class SectionView(View):
    template_name = 'activity/section.html'

    def get(self, request, activity_index, section_index):
        activity = Activity.objects.get(index=activity_index)
        section = Section.objects.get(activity=activity, index=section_index)
        items = Item.objects.filter(section=section)
        context = {'activity': activity, 'section': section, 'items': items, 'user': request.user}
        return render(request, self.template_name, context)


class ItemCreateView(View):
    template_name = 'activity/item_create.html'

    def get(self, request, activity_index, section_index):
        activity = Activity.objects.get(index=activity_index)
        section = Section.objects.get(activity=activity, index=section_index)
        items = Item.objects.filter(section=section)
        context = {'activity':activity, 'section':section, 'items': items}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, section_index):
        activity = Activity.objects.get(index=activity_index)
        section = Section.objects.get(activity=activity, index=section_index)
        items = Item.objects.filter(section=section)
        index = len(items) + 1
        new_item = Item(index=index, section=section, text=request.POST['item_text'], author=request.user)
        new_item.save()
        return redirect('activity:section', activity_index, section_index)


class ItemEditView(View):
    template_name = 'activity/item_edit.html'

    def get(self, request, activity_index, item_pk):
        activity = Activity.objects.get(index=activity_index)
        item = Item.objects.get(pk=item_pk)
        comments = Comment.objects.filter(item=item)
        error_msg = ''
        if len(comments) > 0:
            error_msg = 'People have made comments on this item. You may want to be careful about editing it.'
        context = {'activity': activity, 'item': item, 'comments': comments, 'error': error_msg}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, item_pk):
        activity = Activity.objects.get(index=activity_index)
        item = Item.objects.get(pk=item_pk)
        item.text = request.POST['item_text']
        item.save()
        return redirect('activity:section', activity_index, item.section.index)


class ItemDeleteView(View):
    template_name = 'activity/item_delete.html'

    def get(self, request, activity_index, item_pk):
        activity = Activity.objects.get(index=activity_index)
        item = Item.objects.get(pk=item_pk)
        comments = Comment.objects.filter(item=item)
        error_msg = ''
        if len(comments) > 0:
            error_msg = 'This item already includes comments. Be absolutely sure you want to delete it!'
        context = {'activity': activity, 'item': item, 'comments': comments, 'error': error_msg}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, item_pk):
        activity = Activity.objects.get(index=activity_index)
        item = Item.objects.get(pk=item_pk)
        comments = Comment.objects.filter(item=item)
        if len(comments) > 0:
            for comment in comments:
                comment.delete()
        item_section_index = item.section.index     # better get it before deleting the item
        item.delete()
        return redirect('activity:section', activity.index, item_section_index)


class CommentCreateView(View):
    template_name = 'activity/comment_create.html'

    def get(self, request, activity_index, item_pk):
        activity = Activity.objects.get(index=activity_index)
        item = Item.objects.get(pk=item_pk)
        comments = Comment.objects.filter(item=item)
        context = {'activity': activity, 'item': item, 'comments': comments}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, item_pk):
        item = Item.objects.get(pk=item_pk)
        new_comment = Comment(user=request.user, item=item, text=request.POST['comment_text'])
        new_comment.save()
        return redirect('activity:section', activity_index, item.section.index)


class CommentEditView(View):
    template_name = 'activity/comment_edit.html'

    def get(self, request, activity_index, comment_pk):
        activity = Activity.objects.get(index=activity_index)
        comment = Comment.objects.get(pk=comment_pk)
        item = comment.item
        context = {'activity': activity, 'edit_comment': comment, 'item': item}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, comment_pk):
        comment = Comment.objects.get(pk=comment_pk)
        comment.text = request.POST['comment_text']
        comment.save()
        return redirect('activity:section', activity_index, comment.item.section.index)


class CommentDeleteView(View):
    template_name = 'activity/comment_delete.html'

    def get(self, request, activity_index, comment_pk):
        activity = Activity.objects.get(index=activity_index)
        comment = Comment.objects.get(pk=comment_pk)
        item = comment.item
        context = {'activity': activity, 'delete_comment': comment, 'item': item}
        return render(request, self.template_name, context)

    def post(self, request, activity_index, comment_pk):
        comment = Comment.objects.get(pk=comment_pk)
        item = comment.item     # get the item this comment belongs to before deleting the comment
        comment.delete()
        return redirect('activity:section', activity_index, item.section.index)

ymdisc/activity/templates/activity/comment_create.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Add Comment to "{{ activity }} - {{ section.title }}"</h4>
        </div>
        <div class="card-body">
            <h5>{{ item.text }}</h5>
            {% for comment in comments %}
                <p class="comment-text">{{ comment.user.first_name }} says: {{ comment.text }}</p>
            {% endfor %}
            <form action="{% url 'activity:comment_create' activity.index item.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="item">Enter your comment below:</label>
                    <textarea class="form-control" id="item" name="comment_text" rows="3" autofocus></textarea>
                </div>
                <div class="row justify-content-around">
                    <button class="btn-light btn-lg text-center" type="submit">Submit</button>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:section' activity.index item.section.index %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/comment_delete.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Confirm Deletion</h4>
        </div>
        <div class="card-body">
            <h4 class="card-title">
                Do you really want to delete the highlighted comment?
            </h4>
            <ul>
                {% for comment in item.get_comments %}
                    {% if comment == delete_comment %}
                        <li class="text-warning h5">{{ comment.user.first_name }}: {{ comment.text }}</li>
                    {% else %}
                        <li class="text-comment">{{ comment.user.first_name }}: {{ comment.text }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <form action="{% url 'activity:comment_delete' activity.index delete_comment.pk %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-between">
                    <button class="btn-light btn-lg text-center" type="submit">Yes, Delete it</button>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:comment_edit' activity.index delete_comment.pk %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/comment_edit.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Edit or Delete this Comment for "{{ activity }} - {{ section.title }}"</h4>
        </div>
        <div class="card-body">
            <h5 class="text-main">{{ item.text }}</h5>
            <ul>
                {% for comment in item.get_comments %}
                    {% if comment == edit_comment %}
                        <li class="text-warning h5">{{ comment.user.first_name }}: {{ comment.text }}</li>
                    {% else %}
                        <li class="comment-text">{{ comment.user.first_name }}: {{ comment.text }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <form action="{% url 'activity:comment_edit' activity.index edit_comment.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="form-label" for="comment">Edit your entry below:</label>
                    <textarea class="form-control" id="comment"
                              name="comment_text" rows="3" autofocus>{{ edit_comment.text }}</textarea>
                </div>
                <div class="row justify-content-between">
                    <button class="btn-light btn-lg text-center" type="submit">Save Changes</button>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:section' activity.index item.section.index %}">Cancel</a>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:comment_delete' activity.index edit_comment.pk %}">Delete...</a>

                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/item_create.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Add Discussion Point to "{{ activity }} - {{ section.title }}"</h4>
        </div>
        <div class="card-body">
            {% for item in items %}
                <h5>{{ item.text }}</h5>
            {% endfor %}
            <form action="{% url 'activity:item_create' activity.index section.index %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="item">Enter a new discussion point below:</label>
                    <textarea class="form-control" id="item" name="item_text" rows="3" autofocus></textarea>
                </div>
                <div class="row justify-content-around">
                    <button class="btn-light btn-lg text-center" type="submit">Submit</button>
                    <a class="btn btn-light text-center"
                       href="{% url 'activity:section' activity.index section.index %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/item_delete.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Confirm Deletion</h4>
        </div>
        <div class="card-body">
            <h4 class="card-title">
                Do you really want to delete the following discussion point and all of its comments?
            </h4>
            <h5 class="text-main">{{ item.text }}</h5>
            <ul>
                {% for comment in item.get_comments %}
                    <li class="text-comment">{{ comment.user.first_name }}: {{ comment.text }}</li>
                {% endfor %}
            </ul>
            {% if error %}
                <p class="text-danger h5">{{ error }}</p>
            {% endif %}
            <form action="{% url 'activity:item_delete' activity.index item.pk %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-between">
                    <button class="btn-light btn-lg text-center" type="submit">Yes, Delete it</button>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:item_edit' activity.index item.pk %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/item_edit.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h4>Edit or Delete this Discussion Point to "{{ activity }} - {{ section.title }}"</h4>
        </div>
        <div class="card-body">
            <h5 class="text-main">{{ item.text }}</h5>
            <ul>
                {% for comment in item.get_comments %}
                    <li class="text-comment">{{ comment.user.first_name }}: {{ comment.text }}</li>
                {% endfor %}
            </ul>
            {% if error %}
                <p class="text-danger h5">{{ error }}</p>
            {% endif %}
            <form action="{% url 'activity:item_edit' activity.index item.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="form-label" for="item">Edit your entry below:</label>
                    <textarea class="form-control" id="item"
                              name="item_text" rows="3" autofocus>{{ item.text }}</textarea>
                </div>
                <div class="row justify-content-between">
                    <button class="btn-light btn-lg text-center" type="submit">Save Changes</button>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:section' activity.index item.section.index %}">Cancel</a>
                    <a class="btn btn-light btn-lg text-center"
                       href="{% url 'activity:item_delete' activity.index item.pk %}">Delete...</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/section.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h3>{{ activity }} - {{ section.title }}</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ section.instructions }}</h5>
            {% if section.link_name %}
                <a class="card-title text-main h5" href="{{ section.link }}">Click Here: {{ section.link_name }}</a>
            {% endif %}
            <hr>
            <ul>
                {% for item in items %}
                    {% if item.author == user %}
                        <li class="h5 text-main">
                            {{ item.text }}
                            <a href="{% url 'activity:item_edit' activity.index item.pk %}"> (Edit...)</a>
                        </li>
                    {% else %}
                        <li class="h5 text-main">{{ item.text }}</li>
                    {% endif %}
                    {% for comment in item.get_comments %}
                        {% if comment.user == user %}
                            <p class="text-comment">{{ comment.user.first_name }}: {{ comment.text }}
                                <a class="text-primary"
                                   href="{% url 'activity:comment_edit' activity.index comment.pk %}"> (Edit...)</a>
                            </p>
                        {% else %}
                            <p class="text-comment">{{ comment.user.first_name }}: {{ comment.text }}</p>
                        {% endif %}
                    {% endfor %}
                    <a class="btn btn-light mb-3" href="{% url 'activity:comment_create' activity.index item.pk %}">
                        Make Entry
                    </a>
                    <hr>
                {% endfor %}
            </ul>
            {% if user.is_staff %}
                <a class="btn btn-light" href="{% url 'activity:item_create' activity.index section.index %}">
                    Add New Discussion Point
                </a>
                <hr>
            {% endif %}
            <div class="row justify-content-around">
                <a class="btn btn-light" href="{% url 'activity:welcome' %}">Topic List</a>
                <a class="btn btn-light" href="{% url 'activity:summary' activity.index %}">Section List</a>
            </div>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/summary.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme">
            <h3>Unit {{ activity.index }}: {{ activity }}</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ activity.overview }}</h5>
            <hr>
            <h5 class="card-title">Available Sections:</h5>
            <hr>
            <ul class="card-text">
                {% for section in sections %}
                    <a href="{% url 'activity:section' activity.index section.index %}">
                        <li class="row h4 py-3 mx-auto">
                            Section {{ section.index }} - {{ section.title }}
                        </li>
                    </a>
                {% endfor %}
            </ul>
            <hr>
            <div class="row justify-content-center">
                <a class="btn btn-light" href="{% url 'activity:welcome' %}">Back to Topic List</a>
            </div>
        </div>
    </div>
{% endblock %}

ymdisc/activity/templates/activity/welcome.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header reverse-color-scheme text-center">
            <h3>Topic List</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title">Click on a topic below to add comments about that section of the book.</h5>
            <hr>
            <div class="row">
                <div class="col-md-7">
                    <ul class="card-text">
                        {% for activity in activities %}
                            <a href="{% url 'activity:summary' activity.index %}">
                                <li class="row h4 py-3">
                                    {{ activity.title }}
                                </li>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-md-5">
                    <img class="img-fluid" src="{% static image %}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}